version: "3.5"

services:
  crawler:
    container_name: crawler
    stdin_open: true
    build:
      dockerfile: ./docker/test/Dockerfile
    depends_on:
      - testing_db
    volumes:
      - ./crawler:/app
      - /app/node_modules
  testing_db:
    container_name: testing_db
    image: 'postgres:14.5'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5678:5432
    volumes:
      - ./postgres_testing_data:/var/lib/postgresql/data